pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
        - author=dependabot[bot]
        - author=github-actions[bot]
      - label=dependencies

      - check-success=Build - x86_64-linux
      - check-success=Build - aarch64-linux
    actions:
      merge:
        method: squash
      delete_head_branch:
